var age = 25;
age = true;
console.log(age);
age = "Imane";
console.log(age);
age = { name: "imane", isStudent: false };
console.log(age);
var mixed = [];
mixed.push(25);
mixed.push("imane");
mixed.push(false);
mixed.push(33);
mixed.push("assem");
console.log(mixed);
var esiest;
esiest = { name: "assem", age: 33 };
console.log(esiest);
esiest = { name: 33, age: "assem" };
console.log(esiest);
